version: "3"
services:
  senslog-processing:
    image: senslog-processing
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:800"
    env_file:
      - ./environment.env