# =============================================================
# Application properties
#
enum:
  alert:
    event: FIRST_ENUM

#security:
#  ignored: /**
# =============================================================
# SPRING
#
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    initialization-mode: always
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

# =============================================================
# SERVER
#
server:
    port: 8080
    session:
      cookie:
        unitDesc: UISESSION
